name: Build CI VUE3

on: 
  push:
    branches: [ vue3_dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: install
        run: yarn

      - name: Build
        run: yarn run build
